[pytest]
DJANGO_SETTINGS_MODULE = config.settings.dev
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = 
    --verbose
    --strict-markers
    --cov=apps
    --cov-report=html
    --cov-report=term-missing:skip-covered
